Repository tinkerbell/osie, pull requests merged in 2020-07, with the labels that each got.

#54 Show Makefile some love
  .drone.yml
  .gitignore
  Makefile
  apps/osie-installer-rc
  apps/osie-installer.sh
  apps/rescue-helper-rc
  apps/rescue-helper.sh
  apps/runner-rc
  apps/runner.sh
  apps/workflow-helper-rc
  apps/workflow-helper.sh
  ci/Dockerfile
  rules.mk.j2
  rules.mk.json
  shell.nix
Labels: ready-to-merge

#63 Normalize MTFD string into Micron Technology
  docker/scripts/hardware/utils.py
Labels: ready-to-merge

#64 Gather firmware version and SMART attributes for NVMe
  docker/scripts/hardware/component/disk.py
  docker/scripts/hardware/utils.py
Labels: ready-to-merge

#66 .github: drop, in favor of the org's .github repo
  .github/pull_request_template.md
Labels: ready-to-merge

#69 Remove baremetal_2a5 from exclusion list.
  docker/scripts/deprovision.sh
Labels: ready-to-merge

#62 Upload prs to s3 too
  .drone.yml
  rules.mk.j2
Labels: ready-to-merge

#70 Build latest smartmontools
  docker/Dockerfile
  docker/build-smartmontools.sh
  docker/get-package-list.sh
Labels: ready-to-merge

#75 Gather a better Mellanox model, from partNumber
  docker/scripts/hardware/component/network.py
  docker/scripts/hardware/utils.py
Labels: enhancement, ready-to-merge

#77 Upgrade mlxup to latest version
  docker/lfs/mlxup-aarch64
  docker/lfs/mlxup-x86_64
Labels: ready-to-merge

#78 Added container name for worker
  apps/workflow-helper.sh
Labels: quick-fix
